version: 2.1
orbs:
  docker: circleci/docker@1.7.0
  node: circleci/node@4.7.0

jobs:
  build:
    docker:
      - image: circleci/node:12.9.1-browsers
  
    working_directory: ~/repo
steps:
      - checkout
      
      - restore_cache:
        keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      
      - run: npm install
   
      - save_cache:
        paths:
          - node_modules
          - ~/.npm 
          - ~/.cache
        key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm lint:check
      - run: npm test
